services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: allen_shop
      POSTGRES_USER: allen
      POSTGRES_PASSWORD: allen
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
